# ${build.finalName}
#
# Created by GamerCoder215
# 
#

# Port on which the web server will be hosted
port: 30335

# Required HTTP Headers from client in order to send a valid response
# Set to "NONE" to be ignored (not case-sensitive)
# Headers are case-sensitive
# Values that are not strings will be ignored
# If a header has multiple values, the first one will be seen and nothing else
headers:
  Authorization: NONE

# A key as a parameter inside of the URL.
# If a key is set, it will be required in the URL to have "key={KEY}" in order for it to work.
# It is recommended to set this as some kind of unique password.
key: NONE

listeners:
  -