name: Lightning
main: me.gamercoder215.lightning.Lightning
description: ${project.description}
version: ${spigot.pluginversion}
api-version: ${spigot.apiversion}
author: GamerCoder215
commands:
  lserver:
    description: Lightning Server base command
    aliases: [lightning, lightningserver, lightserver]
  lserverinfo:
    description: Lightning Server information
    aliases: [lightninginfo, lightning-info, light-info]
permissions:
  lightning.server:
    description: All server commands
    default: op
    children:
      lightning.server.info: true
      lightning.server.listener: true
  lightning.server.listener:
    description: Add & Remove Event Listeners
    default: op
  lightning.server.info:
    description: Query server information
    default: op