name: Lightning
main: me.gamercoder215.lightning.Lightning
description: ${project.description}
version: ${spigot.pluginversion}
api-version: ${spigot.apiversion}
author: GamerCoder215
permissions:
  lightning.server:
    description: All server commands
    default: op
    children:
      lightning.server.start: true
      lightning.server.stop: true
      lightning.server.info: true
      lightning.server.listener: true
  lightning.server.listener:
    description: Add & Remove Event Listeners
    default: op
  lightning.server.start:
    description: Start server
    default: op
  lightning.server.stop:
    description: Stop server
    default: op
  lightning.server.info:
    description: Query server information
    default: op